### ISSUE TITLE
Prevent components for rendering before redirect

### ISSUE THREAD

**Issue by gabrielcosi** [PompolutZ/react-firebase-auth-skeleton#4]
I'm using your approach to secure routes with fiirebase auth and roles, but when someone who is not logged in paste a protected route in the url, the component for that path renders and ~1 sec after it redirects to /login. How can I prevent that issue?

**Comment by PompolutZ** [comment]
Hi,

Do you use withAuthorization HOC?

**Comment by gabrielcosi** [comment]
Yes, I am using it, first I thought it could be a problem with my project because I am using routes with layouts and extra stuff, but then I cloned your repository and compiled it and checked the same behavior, you can test it, without logging in, go to the url of a protected route.

**Comment by PompolutZ** [comment]
The issue you experience is here:

```
import React, { useContext, useEffect } from 'react'
import { withRouter } from 'react-router-dom';
import * as ROUTES from '../../constants/routes';
import { FirebaseContext } from '../../firebase';

const withAuthorization = condition => Component => {
    function WithAuthorization(props) {
        const firebase = useContext(FirebaseContext);

        useEffect(() => {
            const releaseAuthListener = firebase.onAuthUserListener(
                authUser => {
                    if(!condition(authUser)) {
                        props.history.push(ROUTES.SIGN_IN);
                    }
                },
                () => props.history.push(ROUTES.SIGN_IN)
            );
    
            return () => releaseAuthListener();
        }, []);
        
        return <Component {...props} />;
    }

    return withRouter(WithAuthorization);
}

export default withAuthorization;
```

As you can see, we render wrapped Component and then asynchronously we check if user logged in, and if not or permission condition is false, then we redirect to SIGN_IN page. 

I can try to fix this issue, but I don't have much time for my hobby stuff right now, so if you find better solution to the problem before me, please feel free to make a pull request :) But I promise I will think about this issue also, because I use this skeleton in at least one of my applications to it will be nice to fix it :)

**Comment by gabrielcosi** [comment]
I'm trying this in the return block
```
<>
      {(authUser) => (condition(authUser) ? <Component {...props} /> : null)}
</>
```
But instead of redirecting to /login it shows a console error
```Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.```

**Comment by PompolutZ** [comment]
Hi @gabrielcosi ,

I have made a change to withAuthorization HOC, so you can pull and try. Don't thinks its the best is possible, but hopefully should resolve you problem.

**Comment by gabrielcosi** [comment]
Thank you, it's working now :)

**Comment by PompolutZ** [comment]
Glad that it worked :) But just note that its just one way of doing things, there is still enough space to improve, so don't hesitate do change things to your liking and of course I welcome you to check latest commit to see what I have done particularity and maybe change it for something even better :)
